### https://reid-projects.com/control-garage-door-with-home-assistant

esphome:
  name: wemos-garage
  on_boot:
    lambda: !lambda |-
      if (id(open_endstop_binary_sensor).state) {
        id(is_open).publish_state(true);
        id(is_jammed).publish_state(false);
        id(garage_door).position = COVER_OPEN;
        id(garage_door).publish_state();
        id(virtual_lock).publish_state(false);
      } else if (id(close_endstop_binary_sensor).state) {
        id(is_open).publish_state(false);
        id(is_jammed).publish_state(false);
        id(garage_door).position = COVER_CLOSED;
        id(garage_door).publish_state();
        id(virtual_lock).publish_state(true);
      } else {
        id(is_open).publish_state(true);
        id(is_jammed).publish_state(true);
        id(garage_door).position = COVER_OPEN;
        id(garage_door).publish_state();
        id(virtual_lock).publish_state(false);
      }

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret wemos_garage_encryption_key

ota:
  password: !secret wemos_garage_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

time:
  - platform: homeassistant
    id: ha_time
  
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "Sygnał WiFi dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Sygnał WiFi Procent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: dht
    pin: GPIO0
    temperature:
      id: dht_temperature
      name: "Temperatura w garażu"
    humidity:
      id: dht_humidity
      name: "Wigotność w garażu"
    update_interval: 60s

switch:
  - platform: template
    name: "Virtual Lock"
    id: virtual_lock
    optimistic: true
  - platform: gpio
    pin: GPIO12
    name: "Door relay"
    id: door_relay
    internal: true
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: door_relay
    
binary_sensor:
  - platform: template
    name: "Brama zablokowana"
    id: is_jammed
    device_class: problem

  - platform: template
    name: "Stan bramy garażowej"
    id: is_open
    device_class: garage_door
    
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Garage Door Close Sensor"
    id: close_endstop_binary_sensor
    internal: true
    on_press:
      - cover.template.publish:
          id: garage_door
          state: CLOSED
          current_operation: IDLE
      - binary_sensor.template.publish:
          id: is_jammed
          state: OFF
      - binary_sensor.template.publish:
          id: is_open
          state: OFF
    on_release: 
      - cover.template.publish:
          id: garage_door
          current_operation: OPENING
          position: 0.5
      - binary_sensor.template.publish:
          id: is_open
          state: ON
      - delay: 22s
      - if:
          condition:
            - and:
              - binary_sensor.is_off: open_endstop_binary_sensor
              - binary_sensor.is_off: close_endstop_binary_sensor
          then: 
            - binary_sensor.template.publish:
                id: is_jammed
                state: ON

  - platform: gpio
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Garage Door Open Sensor"
    id: open_endstop_binary_sensor
    internal: true
    on_press:
      - cover.template.publish:
          id: garage_door
          state: OPEN
          current_operation: IDLE
      - binary_sensor.template.publish:
          id: is_jammed
          state: OFF
    on_release: 
      - cover.template.publish:
          id: garage_door
          current_operation: CLOSING  
          position: 0.5
      - delay: 22s
      - if:
          condition:
            - and:
              - binary_sensor.is_off: close_endstop_binary_sensor
              - binary_sensor.is_off: open_endstop_binary_sensor
          then: 
            - binary_sensor.template.publish:
                id: is_jammed
                state: ON

cover:
  - platform: template
    id: garage_door
    name: "Brama garażowa"
    device_class: garage
    has_position: true
    open_action:
      - if:
          condition:
            - and:
              - switch.is_off: virtual_lock
              - binary_sensor.is_on: close_endstop_binary_sensor
          then: 
            - switch.turn_on: door_relay
    close_action:
      - if:
          condition:
            - and:
              - switch.is_off: virtual_lock
              - binary_sensor.is_on: open_endstop_binary_sensor
          then: 
            - switch.turn_on: door_relay
    stop_action:
      - if:
          condition:
            - and:
              - switch.is_off: virtual_lock
              - binary_sensor.is_off: close_endstop_binary_sensor
              - binary_sensor.is_off: open_endstop_binary_sensor
          then: 
            - switch.turn_on: door_relay